<?php
return [
'name' => 'eCommerce',
'website' => 'http://localhost:8000',
'company_phone' => '22222222',
'email_from' => 'noreply@eccomerce.cl',
'maintenance_mode' => '0',
'currency' => 'CLP',
'shop_min_amount' => '1000',
'shipping_method' => '2',
'shipping_default_value' => '5000',
'shipping_amount_min' => '2000',
'to_go' => '1',
'social_facebook' => 'https://www.facebook.com/',
'social_instagram' => 'https://www.instagram.com/',
'social_twitter' => '#',
'social_youtube' => '#',
'social_whatsapp' => '#',
'payment_method_cash' => '1',
'payment_method_transfer' => '1',
'payment_method_paypal' => '0',
'payment_method_credit_card' => '0',
'products_per_page' => '100',
'products_per_page_random' => '100',
'server_uploads_paths' => 'Whatever',
'server_uploads_user_paths' => 'Whatever',
'server_webapp_path' => 'Whatever',
]
?>
